#!/bin/bash

set -e

cd `dirname $0`

pip install --upgrade virtualenv

virtualenv .

# I don't know why this is created.
rm -rf local

source bin/activate
pip install --upgrade twisted pyephem pylint mock pysnmp
easy_install --upgrade pytz
